{% set name = "nvtop" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/syllo/{{ name }}/archive/{{ version }}.tar.gz
  sha256: de3d7b6a889f886f3bc28c15c3c34cfb6fcb7cb7ebc9a0cc36c3c77d837029b1

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - automake
    - libtool
    - cmake
    - make
    - cudatoolkit-dev
    - {{ compiler('c') }}
  host:
    - ncurses
    - cudatoolkit-dev

  run:
    - ncurses
    - cudatoolkit-dev

test:
  commands:
    - nvtop --version

about:
  home: https://github.com/syllo/nvtop/
  license: GPL-3.0
  license_file: COPYING
  summary: Nvtop stands for NVidia TOP, a (h)top like task monitor for NVIDIA GPUs. It can handle multiple GPUs and print information about them in a htop familiar way.

extra:
  recipe-maintainers:
    - andrewannex

